package fuse.ejemplo.servicio;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * Esto es una prueba...
 *
 * This class was generated by Apache CXF 3.0.15
 * 2017-11-08T16:34:59.514-03:00
 * Generated source version: 3.0.15
 * 
 */
@WebServiceClient(name = "ServicioPrueba", 
                  wsdlLocation = "http://192.168.56.1:8080/WsPrueba.asmx?WSDL",
                  targetNamespace = "http://Ponyo.cl/") 
public class ServicioPrueba extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://Ponyo.cl/", "ServicioPrueba");
    public final static QName ServicioPruebaSoap12 = new QName("http://Ponyo.cl/", "ServicioPruebaSoap12");
    public final static QName ServicioPruebaSoap = new QName("http://Ponyo.cl/", "ServicioPruebaSoap");
    static {
        URL url = null;
        try {
            url = new URL("http://192.168.56.1:8080/WsPrueba.asmx?WSDL");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ServicioPrueba.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://192.168.56.1:8080/WsPrueba.asmx?WSDL");
        }
        WSDL_LOCATION = url;
    }

    public ServicioPrueba(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ServicioPrueba(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ServicioPrueba() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ServicioPrueba(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ServicioPrueba(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ServicioPrueba(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    

    /**
     *
     * @return
     *     returns ServicioPruebaSoap
     */
    @WebEndpoint(name = "ServicioPruebaSoap12")
    public ServicioPruebaSoap getServicioPruebaSoap12() {
        return super.getPort(ServicioPruebaSoap12, ServicioPruebaSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ServicioPruebaSoap
     */
    @WebEndpoint(name = "ServicioPruebaSoap12")
    public ServicioPruebaSoap getServicioPruebaSoap12(WebServiceFeature... features) {
        return super.getPort(ServicioPruebaSoap12, ServicioPruebaSoap.class, features);
    }
    /**
     *
     * @return
     *     returns ServicioPruebaSoap
     */
    @WebEndpoint(name = "ServicioPruebaSoap")
    public ServicioPruebaSoap getServicioPruebaSoap() {
        return super.getPort(ServicioPruebaSoap, ServicioPruebaSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ServicioPruebaSoap
     */
    @WebEndpoint(name = "ServicioPruebaSoap")
    public ServicioPruebaSoap getServicioPruebaSoap(WebServiceFeature... features) {
        return super.getPort(ServicioPruebaSoap, ServicioPruebaSoap.class, features);
    }

}
